if game.PlaceId == 126884695634066 then
  loadstring(game:HttpGet("https://raw.githubusercontent.com/Marukulaes/Attack-Hub/refs/heads/main/Grow%20A%20Graden"))()


elseelseif game.PlaceId == 103754275310547 then
  loadstring(game:HttpGet("https://raw.githubusercontent.com/Dummyrme/AttackHub/refs/heads/main/huntyzombie.lua"))()

elseif game.PlaceId == 86076978383613 then
  loadstring(game:HttpGet("https://raw.githubusercontent.com/Dummyrme/AttackHub/refs/heads/main/huntyzombie.lua"))()
end
